### ISSUE TITLE
COUCHBASE: too many FDs. Cannot have socket > FD_SETSIZE. Use other I/O plugin

### ISSUE THREAD

**Issue by yagnasrinath** [couchbaselabs/libcouchbase-cxx#18]
@mnunberg Can the library switch to epoll instead of select? we have been waiting for it to happen, Our architecture doesn't enable us to use other plugins. if the switch can be done, when can we expect the switch to epoll?

**Comment by mnunberg** [comment]
I really don’t see a use case for supporting epoll directly if it’s already supported by means of libevent. The point of the ‘select’ plugin is to have a single plugin that’s debuggable on all platforms (including Windows). Is there a reason why you cannot use libevent? If you’re using boost (or ok with using it) there’s a plugin using that as well.

**Comment by yagnasrinath** [comment]
we did try libuv, but we found two issues:
1. The calls were not getting scheduled until I force update the tick count  with uv_update_time() and it was too slow. May be that we were not using it properly.
2. Is there any way to force timeout on async api, to not call the callback, if the time between the request fired and response is later than certain milliseconds? we tried to achieve that, but it was not working well. Is there any easy way to achieve that?

**Comment by mnunberg** [comment]
1. Should work perfectly with lcb_wait etc. - we unit test the UV plugin in that manner and it works fine. Maybe try an older version of UV (e.g. from 2014 or so)? I'm curious if that makes a difference - as that's the version the library was developed against.

2. By async API you mean the one in libcouchbase-cxx? I can maybe do that a bit later to e.g. skip invocation if it timed out.. but then.. how would you be notified of the error?

For the actual C API it wouldn't make sense, since there are resources that presumably need to be cleaned up. The place to do that would be the callback.

**Comment by yagnasrinath** [comment]
Thank you @mnunberg for prompt responses. Really appreciate them. I will give libuv a try again.
I meant the C API. But since you said that it is not possible on C side, if we have poll/kqueue implementation, we achieve the same with our current architecture. Also I am curious to know about couchbase protocol spec. But the link on the website seems to be broken. http://www.couchbase.com/docs/couchbase-manual-1.8/couchbase-client-development.html

Is there any other place where I can access it?

**Comment by mnunberg** [comment]
Closing this - issue not specific to libcouchbase-cxx
